### PR TITLE
fix: sticky footer

### LINKED ISSUE #36: Fix sticky footer when the page is quite empty
The footer can be sticky to the bottom.

References:

- https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer

Expectation:

image

Current:

image

### PR DESCRIPTION
**Pull request by ar-rohman**
## Description

Place footer to bottom when page content quite empty.

## Related Issues

Close #36

### Before This PR

image

### After This PR

image

### CODE REVIEW

File: app/components/shared/site-footer.tsx [hunk 1]
```diff
@@ -3,7 +3,7 @@ import { Navigation } from "./navigation";
 
 export function SiteFooter() {
   return (
-    <footer className="container flex-col mx-auto gap-14 xs:mt-12 lg:mt-32">
```
Comment (fikrialwan) [inline app/components/shared/site-footer.tsx:6]: I think `gap-14` is still needed because the Figma design shows space between the navigation and the footer content.
image

Comment (ar-rohman) [reply app/components/shared/site-footer.tsx:6]: Oh, my bad. Is the top margin still needed too?

Comment (fikrialwan) [reply app/components/shared/site-footer.tsx:6]: I think there is no problem with the top margin because the footer already has padding.

File: app/root.tsx [hunk 2]
```diff
@@ -22,7 +22,7 @@ export function Layout({ children }: { children: React.ReactNode }) {
       </head>
       <body className="bg-[#15181D] text-slate-50">
         <SiteNavigation />
-        {children}
+        <main className="min-h-[calc(100vh-304px)]">{children}</main>
```
Comment (fikrialwan) [inline app/root.tsx]: just worried, if there was a change in the footer height, did the code here also need to be updated? 
Why didn't you use flex like in the reference https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/ instead of using a static min-height?

Comment (ar-rohman) [reply app/root.tsx]: got it

File: app/components/shared/site-navigation.tsx [hunk 3]
```diff
@@ -3,7 +3,7 @@ import { Navigation } from "./navigation";
 
 export function SiteNavigation() {
   return (
-    <div className="flex justify-center items-center">
+    <div className="flex justify-center items-center flex-none">
```
Comment (iamyuu) [inline app/components/shared/site-navigation.tsx]: I don't think adding `flex-none` is necessary

Comment (ar-rohman) [reply app/components/shared/site-navigation.tsx]: just removed

**Comment by mhaidarhanif** [comment]
Looks good? @reactjs-id/website
